# Codemagic configuration for building Uztools iOS app
workflows:
  ios-build:
    name: Uztools iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hbncompany.uztools
      xcode: latest
      cocoapods: default
      vars:
        XCODE_SCHEME: "Uztools" # Replace with your Xcode scheme name
        XCODE_PROJECT: "Uztools.xcodeproj" # Replace with your Xcode project or workspace file
        XCODE_CONFIGURATION: "Release"
        PROVISIONING_PROFILE_NAME: "UztoolsAppStoreProfile" # Replace with your provisioning profile name
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "No Podfile found, skipping CocoaPods installation"
          fi
      - name: Build and archive iOS app
        script: |
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration "$XCODE_CONFIGURATION" \
                     -archivePath ./build/Uztools.xcarchive \
                     clean archive \
                     CODE_SIGN_STYLE=Manual \
                     CODE_SIGN_IDENTITY="iPhone Distribution" \
                     PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_NAME"
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath ./build/Uztools.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath ./build
    artifacts:
      - build/*.ipa
      - build/*.xcarchive
    publishing:
      email:
        recipients:
          - user@example.com # Replace with your email
        notify:
          success: true
          failure: true
